config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'groups#index'
  resources :groups, except: [:show] do
    collection do
      get :user_search
    end
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true

  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages

  accepts_nested_attributes_for :users
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  mount_uploader  :image, ImageUploader
  validates :body, presence: true

  belongs_to :user
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
before_action :authenticate_user!
before_action :set_group, only: [:edit, :update]

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_user_params)
    if @group.save
      redirect_to root_path, notice: "新しいチャットグループが作成されました。"
    else
      flash.now[:alert] = "グループ作成に失敗しました。"
      render :new
    end
  end

  def edit
    @members = @group.users.where.not(id: current_user)
  end

  def update
    if @group.update(group_user_params)
      redirect_to root_path, notice: "チャットグループが編集されました。"
    else
      flash.now[:alert] = "グループ編集に失敗しました。"
      render :edit
    end
  end

  def user_search
    search_word = params[:content]
    @users = User.where("name LIKE ?", "%" + search_word + "%")
    respond_to do |format|
      format.json
    end
  end

  private
  def group_user_params
    params.require(:group).permit(:name, :user_ids => [])
  end

  def set_group
    @group = Group.find(params[:id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: [:index, :create]

  def index
    @message = Message.new
    @messages = @group.messages
    @users = @group.users
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path }
        format.json
      end
    else
      redirect_to group_messages_path, flash: { alert: "本文がないため、送信できませんでした。"}
    end
  end

  private
  def message_params
    params.require(:message).permit(:body, :image).merge(user_id: current_user.id, group_id: params[:group_id])
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_group.html.haml
.chat-group-form__field.clearfix
  .chat-group-form__field--left
    = f.label :グループ名, class: 'chat-group-form__label'
  .chat-group-form__field--right
    = f.text_field :name, placeholder: "グループ名を入力してください", class: 'chat-group-form__input', id: 'chat-group-form__name'
.chat-group-form__field.clearfix
  .chat-group-form__field--left
    = f.label :チャットメンバーを追加, class: 'chat-group-form__label'
  .chat-group-form__field--right
    %input.chat-group-form__input#chat-group-form__user{placeholder: "ユーザー名を入力してください", autocomplete: 'off'}
    %ul.user-search-result
.chat-group-form__field.clearfix
  .chat-group-form__field--left
    = f.label :チャットメンバー, class: 'chat-group-form__label'
  .chat-group-form__field--right
    %ul.chat-group-user
      %li.list
        = current_user.name
        %input{ type: "hidden", name: "group[user_ids][]", value: current_user.id }
      - if @group.users
        = render partial: 'members', collection: @members, as: "user"

.chat-group-form__field.clearfix
  .chat-group-form__field--left
  .chat-group-form__field--right
    = f.submit value: "Save", class: 'btn chat-group-form__action-btn'

app/views/groups/_members.html.haml
%li.list.select_member{ user_id: user.id, user_name: user.name }
  = user.name
  %span.chat-group-user__btn--remove
    削除
  %input{ type: "hidden", name: "group[user_ids][]", value: user.id }

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  - if @group.errors.any?
    .chat-group-form__errors
      %h2
        =pluralize(@group.errors.count, "error prohibited this group from being saved:")
      %ul
        - @group.errors.full_messages.each do |msg|
          %li=msg
  #edit_chat_group.edit_chat_group
  = form_for(@group) do |f|

    = render partial: 'group', locals: { f: f }

app/views/groups/index.html.haml
.main-container
  .left-container
    #user-info-box
      %p#user-info-box__name
        = current_user.name
      #user-info-box__icon-wrapper
        = link_to new_group_path do
          %i.fa.fa-edit.fa-lg
        = link_to edit_user_registration_path do
          %i.fa.fa-cog.fa-lg
    #group-wrapper
      = render partial: 'shared/group', collection: current_user.groups

  .right-container

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  - if @group.errors.any?
    .chat-group-form__errors
      %h2
        =pluralize(@group.errors.count, "error prohibited this group from being saved:")
      %ul
        - @group.errors.full_messages.each do |msg|
          %li=msg
  #new_chat_group.new_chat_group
  = form_for(@group) do |f|

    = render partial: 'group', locals: { f: f }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: "text/html; charset=UTF-8", http: { equiv: "Content-Type" } }/
    %title ChatSpace
    = stylesheet_link_tag    'application', media: 'all', data: { turbolinks: { track: true } }
    = javascript_include_tag 'application', data: {turbolinks: { track: true } }
    = csrf_meta_tags
  %body
    %p#notice= notice
    %p#alert= alert
    = yield

app/views/messages/_msg.html.haml
.message-box
  %p.message-box__sender
    = msg.user.name
    %span.message-box__datetime
      = msg.created_at.to_s(:created_at)
  %p.message-box__content
    = msg.body
  .message-box__image
    - if msg.image.present?
      = image_tag msg.image.url

app/views/messages/index.html.haml
.main-container
  .left-container
    #user-info-box
      %p#user-info-box__name
        = current_user.name
      #user-info-box__icon-wrapper
        = link_to new_group_path do
          %i.fa.fa-edit.fa-lg
        = link_to edit_user_registration_path do
          %i.fa.fa-cog.fa-lg
    #group-wrapper
      = render partial: 'shared/group', collection: current_user.groups

  .right-container
    #group-info-box
      %p#group-info-box__name
        = @group.name
      %p#group-info-box__member
        Members: 
        = @users.map(&:name).join(" ")
      = link_to edit_group_path(@group) do
        #group-info-box__edit-btn
          Edit
    #message-wrapper
      = render partial: 'msg', collection: @messages

    #texting-box
      = form_for([@group, @message], html: { id: "texting-form" }) do |f|
        = f.text_field :body, placeholder: "type a message", size: "20", id: "texting-box__input"
        = f.label :image do
          = f.file_field :image, id: "texting-box__photo-file"
          = fa_icon "image", id: "texting-box__photo-icon"
        = f.submit value: "Send", id: "texting-box__send-btn"

app/views/shared/_group.html.haml
#group-box
  = link_to group_messages_path(group.id) do
    #group-box__name
      = group.name
    #group-box__message
      - if group.messages.present?
        = group.messages.last.body
      - else
        = "No message"

app/views/users/edit.html.erb
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f|
        = devise_error_messages!
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .field
          .field-label
            = f.label :password
            %i (変更したくない場合は、空白のままにしておいてください)
          .field-input
            = f.password_field :password, autocomplete: "off"
        .field
          .field-label
            = f.label :password_confirmation
          .field-input
            = f.password_field :password_confirmation, autocomplete: "off"
        .field
          .field-label
            = f.label :current_password
            %i (変更には現在のパスワードの入力が必要です)
          .field-input
            = f.password_field :current_password, autocomplete: "off"
        .actions
          = f.submit "Update", class: 'btn'